Url_navigation2/urls.py
from django.contrib import admin
from django.urls import path, include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/urls.py
from django.urls import path
from app1.views import *
app_name='first'
urlpatterns = [
    path('index/',index,name='index'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='second'

urlpatterns = [
    path('page/',page,name='page'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def page(request):
    return render(request,'page.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>specific URL</title>
</head>
<body>
    <center>
    <h1>I am creating url_navigation</h1>
    <h1>This is the reponsive navigation page</h1>
    <a href="{% url 'second:page' %}">click here</a>
</center>
</body>
</html>

templates/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>second reponsive page</title>
</head>
<body>
    <center>
        <h1>This is second page</h1>
        <h1>MOve to index page</h1>
        <a href="{% url 'first:index' %}">Click here</a>
    </center>
</body>
</html>